# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-22 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='desciption',
            field=models.TextField(default='tdftjxjxjxkc g   go pgogugyifid'),
            preserve_default=False,
        ),
    ]
