# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import policies.models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='document',
            field=models.FileField(upload_to=policies.models.upload_policy_file),
        ),
    ]
