# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-07 16:11
from __future__ import unicode_literals

import activities.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Activity Category',
                'verbose_name_plural': 'Activity Categories',
            },
        ),
        migrations.CreateModel(
            name='ActivitySheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to=activities.models.upload_activity_image)),
                ('desciption', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Re-occuring Start date')),
                ('once_date', models.DateField(blank=True, null=True, verbose_name='One Off Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_file', to='activities.ActivityCategory')),
            ],
            options={
                'verbose_name': 'Activity Sheet',
                'verbose_name_plural': 'Activity Sheets',
            },
        ),
    ]
