# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-07 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20190607_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysheet',
            name='slots',
            field=models.IntegerField(default=33),
            preserve_default=False,
        ),
    ]
