# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-08 14:25
from __future__ import unicode_literals

import activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activitysheet_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('document', models.FileField(blank=True, help_text='Upload any material for the day', null=True, upload_to=activities.models.upload_activity_image)),
                ('activities', models.TextField()),
                ('required', models.TextField(blank=True, help_text='For any requiremenrs for the students e.g. lunch, spare clothes', null=True)),
                ('transport', models.TextField(blank=True, help_text='Pick up/Drop off points', null=True)),
                ('slots', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Day Activities',
                'verbose_name_plural': 'Activity Schedule',
            },
        ),
        migrations.RemoveField(
            model_name='activitysheet',
            name='category',
        ),
        migrations.DeleteModel(
            name='ActivityCategory',
        ),
        migrations.DeleteModel(
            name='ActivitySheet',
        ),
    ]
