# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-08 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20190608_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityschedule',
            name='activities',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='required',
            field=models.TextField(blank=True, help_text='For any requirements for the students e.g. lunch, spare clothes', null=True),
        ),
    ]
