# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 19:47
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_bio',
            name='bio',
            field=tinymce.models.HTMLField(default='u fiyf if og piiyd tdtu i o [ up youy uti ru e tgd uyfiyyb d7d rxtx c viuh'),
            preserve_default=False,
        ),
    ]
