# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_bio',
            name='staff_image',
            field=models.ImageField(upload_to=staff.models.upload_staff_img),
        ),
    ]
