# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-01 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_bio_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='rank',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
