# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=home.models.upload_share_img)),
            ],
            options={
                'verbose_name': 'Slide Image',
                'verbose_name_plural': 'Slide Images',
            },
        ),
    ]
