# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/background')),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Background',
                'verbose_name_plural': 'Background Images',
            },
        ),
        migrations.CreateModel(
            name='EmailLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Email Link',
                'verbose_name_plural': 'Email Link',
            },
        ),
        migrations.CreateModel(
            name='FacebookLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Facebook Link',
                'verbose_name_plural': 'Facebook Link',
            },
        ),
        migrations.CreateModel(
            name='HomeBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField(max_length=260)),
            ],
            options={
                'verbose_name': 'Home Box',
                'verbose_name_plural': 'Home Boxes',
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Home Articles',
            },
        ),
        migrations.CreateModel(
            name='HomeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Home Title ',
            },
        ),
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/home_slides')),
            ],
            options={
                'verbose_name': 'Slide Image',
                'verbose_name_plural': 'Slide Images',
            },
        ),
    ]
