# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(upload_to=home.models.upload_home_img),
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='img',
            field=models.ImageField(upload_to=home.models.upload_home_img),
        ),
    ]
