# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Home Articles ',
            },
        ),
    ]
