# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hometitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField(max_length=260)),
            ],
            options={
                'verbose_name': 'Home Box',
                'verbose_name_plural': 'Home Boxes',
            },
        ),
    ]
