# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-06 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190522_1605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeBox',
            new_name='HomeBlurb',
        ),
        migrations.DeleteModel(
            name='BackgroundImage',
        ),
        migrations.AlterModelOptions(
            name='homeblurb',
            options={'verbose_name': 'Home Blurb', 'verbose_name_plural': 'Home Blurbs'},
        ),
    ]
