# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_facebooklink'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Email Link',
                'verbose_name_plural': 'Email Link',
            },
        ),
    ]
