# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_emaillink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecontent',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Home Articles'},
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
