# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='email',
            field=models.CharField(max_length=300),
        ),
    ]
