# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 23:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_auto_20190305_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='staffcontact',
            name='email',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='staffcontact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
