# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_auto_20190305_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Opening Time',
                'verbose_name_plural': 'Opening Times',
            },
        ),
    ]
