# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0004_opentimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='opentimes',
            name='day',
            field=models.CharField(default='wqef', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opentimes',
            name='times',
            field=models.CharField(default='wegfwqef', max_length=400),
            preserve_default=False,
        ),
    ]
