# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Info Article',
            },
        ),
        migrations.CreateModel(
            name='Sponsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/sponsers')),
            ],
            options={
                'verbose_name': 'Sponser',
                'verbose_name_plural': 'Sponsers',
            },
        ),
        migrations.CreateModel(
            name='StickyNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/sticky')),
            ],
            options={
                'verbose_name': 'Sticky Note',
                'verbose_name_plural': 'Sticky Notes',
            },
        ),
    ]
