# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import information.models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsers',
            name='image',
            field=models.ImageField(upload_to=information.models.upload_info_img),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=information.models.upload_info_img),
        ),
    ]
