# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-13 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundraisingTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('target', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
