# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-07 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundraisingtarget',
            options={'verbose_name': 'Fundraising Campaign', 'verbose_name_plural': 'Fundraising Campaign'},
        ),
    ]
