# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-13 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
            },
        ),
        migrations.AlterModelOptions(
            name='fundraisingtarget',
            options={'verbose_name': 'Fundraising Target', 'verbose_name_plural': 'Fundraising Targets'},
        ),
        migrations.AddField(
            model_name='fundraisingtarget',
            name='active',
            field=models.BooleanField(default='1'),
            preserve_default=False,
        ),
    ]
