# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-01 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='donation',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
