# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-22 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0002_auto_20190113_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fundraising.FundraisingTarget'),
            preserve_default=False,
        ),
    ]
