# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-01 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0003_donations_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraisingtarget',
            name='picture_1',
            field=models.ImageField(blank=True, null=True, upload_to='fundraising'),
        ),
        migrations.AddField(
            model_name='fundraisingtarget',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='fundraising'),
        ),
        migrations.AddField(
            model_name='fundraisingtarget',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='fundraising'),
        ),
    ]
