# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-01 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0004_auto_20190201_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraisingtarget',
            name='picture_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/fundraising'),
        ),
        migrations.AlterField(
            model_name='fundraisingtarget',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/fundraising'),
        ),
        migrations.AlterField(
            model_name='fundraisingtarget',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/fundraising'),
        ),
    ]
