# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-01 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0006_auto_20190201_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraisingtarget',
            name='picture_1',
        ),
        migrations.RemoveField(
            model_name='fundraisingtarget',
            name='picture_2',
        ),
        migrations.RemoveField(
            model_name='fundraisingtarget',
            name='picture_3',
        ),
        migrations.AddField(
            model_name='fundraisingtarget',
            name='image_1',
            field=models.ImageField(default='wge', upload_to='images/fundraising'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundraisingtarget',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Not required', null=True, upload_to='images/fundraising'),
        ),
        migrations.AddField(
            model_name='fundraisingtarget',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Not required', null=True, upload_to='images/fundraising'),
        ),
    ]
