# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-08 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0007_auto_20190201_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='stripe_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
