# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desription', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Cookie',
                'verbose_name_plural': 'Cookies',
            },
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Cookie page info',
            },
        ),
    ]
