# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-22 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0002_privacy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookies',
            options={'verbose_name': 'Cookie', 'verbose_name_plural': 'Cookies'},
        ),
        migrations.AlterModelOptions(
            name='privacy',
            options={'verbose_name': 'Info', 'verbose_name_plural': 'Cookie page info'},
        ),
    ]
